export const LABELS = Object.freeze({
   institutions: 'Instituciones',
   institution: 'Institución',
   bussinessName: 'Nombre comercial',
   nit: 'NIT',
   legalRepresentative: 'Representante legal',
   ciLegalRepresentative: 'CI representante legal',
   billingName: 'Nombre de facturación',
   clientType: 'Tipo de cliente',
   businessName: 'Nombre comercial',
   institutionName: 'Nombre de la institución',
   institutionAddress: 'Dirección de la institución',
   institutionPhoneNumber: 'Teléfono de la institución',
   account: 'Cuenta',
   yes: 'Si',
   no: 'No',
   minerals: 'Minerales',
   advances: 'Anticipos',
   advance: 'Anticipo',
   mineral: 'Mineral',
   loads: 'Cargas',
   load: 'Carga',
   typeMineral: 'Tipo de mineral',
   cooperatives: 'Cooperativas',
   cooperative: 'Cooperativa',
   lots: 'Lotes',
   lot: 'Lote',
   symbol: 'Símbolo',
   lotExternal: 'Lote externo',
   internalLot: 'Lote interno',
   typeMinerals: 'Tipos de minerales',
   mines: 'Minas',
   mine: 'Mina',
   purpose: 'Propósito',
   delete: 'Eliminar',
   observation: 'Observación',
   cancelInvoice: 'Anular factura',
   getInto: 'Ingresar',
   weight: 'Peso',
   weightKg: 'Peso (Kg)',
   exchangeRate: 'Tipo de cambio',
   percentage: 'Porcentaje',
   quotation: 'Cotización',
   dmSilver: 'D.M. Plata',
   metricWetKilograms: 'K.M.H.',
   solidMetricTonnes: 'T.M.S.',
   solidMetricKilograms: 'K.M.S.',
   humidityPercentage: '% de humedad',
   auxiliary: 'Auxiliar',
   numberSacks: 'Número de sacos',
   liquidations: 'Liquidaciones',
   sackLiquidations: 'Liquidaciones de sacos',
   liquidation: 'Liquidación',
   nim: 'NIM',
   configurations: 'Configuraciones',
   value: 'Valor',
   uploadFile: 'Subir archivo',
   consolidationDay: 'Día de consolidación',
   activity: 'Actividad',
   product: 'Producto',
   sivelCode: 'Código SIVEL',
   user: 'Usuario',
   password: 'Contraseña',
   sivelName: 'Nombre SIVEL',
   externalCode: 'Código externo',
   externalId: 'ID externo',
   currencyCoreId: 'ID moneda de Núcleo',
   documentTypeCoreId: 'ID tipo de documento de Núcleo',
   detail: 'Detalle',
   concept: 'Concepto',
   paymentType: 'Tipo de pago',
   paymentedBy: 'Pagado por',
   paymentBy: 'Pagar por',
   checkNumber: 'Número de cheque',
   newPassword: 'Nueva contraseña',
   confirmationPassword: 'Confirmar contraseña',
   receiptType: 'Tipo de recibo',
   receiptCode: 'Código de recibo',
   conceptId: 'ID de concepto',
   conciliation: 'Conciliación',
   conciliationAmount: 'Monto conciliado',
   item: 'Item',
   finalAmount: 'Monto final',
   conceptCode: 'Código de concepto',
   conceptName: 'Nombre de concepto',
   isHomologated: 'Esta homologado?',
   branch: 'Sucursal',
   pointOfSale: 'Punto de venta',
   branchSivel: 'Sucursal Sivel',
   pointOfSaleSivel: 'Punto de venta Sivel',
   coreCompanyId: 'ID empresa de Núcleo',
   activityCode: 'Código de actividad',
   productCode: 'Código de producto',
   systemCode: 'Código de sistema',
   homologation: 'Homologación',
   system: 'Sistema',
   modeLight: 'Modo claro',
   modeDark: 'Modo oscuro',
   itemTypeCode: 'Código de tipo de item',
   itemType: 'Tipo de item',
   productDetail: 'Detalle de producto',
   expenseIncomeConcept: 'Concepto de ingreso/gasto',
   currencyCore: 'Moneda de Núcleo',
   currencySivel: 'Moneda de Sivel',
   reasonCancel: 'Motivo de cancelación',
   companySivel: 'Empresa de Sivel',
   documentTypeSivel: 'Tipo de documento de Sivel',
   invoiceTypeSivel: 'Tipo de factura de Sivel',
   invoiceNumber: 'Número de factura',
   issueNumber: 'Número de conciliación',
   companyCore: 'Empresa de Núcleo',
   company: 'Empresa',
   clientName: 'Nombre cliente',
   externalLot: 'Lote externo',
   clientDocNumber: 'Número documento cliente',
   clientEmail: 'Correo cliente',
   paymentMethod: 'Método de pago',
   actions: 'Acciones',
   total: 'Total',
   totalImport: 'Importe total',
   totalDiscounts: 'Total descuentos',
   liquidPayable: 'Líquido pagable',
   firstAdvance: 'Primer anticipo',
   secondAdvance: 'Segundo anticipo',
   transportationBonus: 'Bono de transporte',
   month: 'Mes',
   year: 'Año',
   reason: 'Motivo',
   totals: 'Totales',
   giftCard: 'Tarjeta de regalo (Gift card)',
   discount: 'Descuento',
   discounts: 'Descuentos',
   documentTypeCore: 'Tipo de documento de Núcleo',
   invoiceType: 'Tipo de factura',
   totalConciliatedAmount: 'Monto total conciliado',
   codeSivel: 'Código Sivel',
   lawSilver: 'Ley Plata',
   lawZinc: 'Ley Zinc',
   lawLead: 'Ley Plomo',
   department: 'Departamento',
   code: 'Código',
   lotCode: 'Código de lote',
   taxCreditIVA: 'Crédito fiscal iva',
   taxDebitIVA: 'Débito fiscal iva',
   cuf: 'CUF',
   customer: 'Cliente',
   nameOrSocialReason: 'Nombre / Razón social',
   companyDepartment: 'Departamento Contable',
   currency: 'Moneda',
   date: 'Fecha',
   totalNationalExpensesFob: 'Total costos y gastos nacionales',
   totalInternationalExpensesCost: 'Total Costos y gastos internacionales',
   createdBy: 'Creado por',
   updatedBy: 'Actualizado por',
   totalDetail: 'Total detalle',
   totalGeneral: 'Total general',
   totalAmountToPay: 'Total a pagar',
   totalAmountOriginal: 'Monto total original',
   amountOriginal: 'Monto total original',
   creationDate: 'Fecha creación',
   issueDate: 'Fecha emisión',
   email: 'Correo electrónico',
   role: 'Role',
   additionalInfo: 'Información adicional',
   nationalExpensesCost: 'Gastos nacionales',
   internationalExpensesCost: 'Gastos internacionales',
   numberPackagesDescription: 'Descripción del número de paquete',
   address: 'Dirección',
   supplierGroup: 'Grupo de proveedor',
   suppliers: 'Proveedores',
   supplier: 'Proveedor',
   admissionDate: 'Fecha de ingreso',
   lotType: 'Tipo de lote',
   cotization: 'Cotización',
   phone: 'Teléfono',
   logo: 'Logo',
   docNumber: 'Número de documento',
   totalAmountExchanged: 'Monto total cambiado',
   docType: 'Tipo de documento',
   clientDocType: 'Tipo de documento cliente',
   complement: 'Complemento',
   customerMarket: 'Mercado de clientes',
   status: 'Estado',
   creditDebitNumber: 'Número de crédito/débito',
   cashAAmountCreditDebit: 'Monto efectivo crédito/débito',
   amountDiscountCreditDebit: 'Descuento crédito/débito',
   totalRefundedAmount: 'Monto total reintegrado',
   marketType: 'Tipo de mercado',
   destinationPlace: 'Lugar de destino',
   destinationPort: 'Puerto de destino',
   newAmount: 'Nuevo monto',
   countryCode: 'Código de país',
   countryCodeSivel: 'Código de país de Sivel',
   incoterm: 'INCOTERM',
   name: 'Nombre',
   nameCore: 'Nombre de Núcleo',
   silver: 'Plata',
   zinc: 'Zinc',
   lead: 'Plomo',
   budgetSummary: 'Ppto. Recurso',
   budgetExpense: 'Ppto. Gasto',
   socialReason: 'Razón social',
   incomeConcept: 'Concepto de venta',
   import: 'Importe',
   budgetItem: 'Partida',
   registerManager: 'Responsable de registro',
   expense: 'Gasto',
   resource: 'Recurso',
   conceptSale: 'Concepto de venta',
   disaccount: 'Descuento',
   initials: 'Iniciales',
   organizationalUnit: 'Unidad Organizativa',
   programmaticCategory: 'Categoría Programática',
   program: 'Programa',
   project: 'Proyecto',
   persons: 'Personas',
   person: 'Persona',
   fundingSource: 'Fuente de financiamiento',
   fundingOrganization: 'Organización financiadora',
   programmaticStructure: 'Estructura Programática',
   regional: 'Regional',
   financier: 'Financiador',
   totalAmount: 'Monto total',
   subTotal: 'Subtotal',
   description: 'Descripción',
   liquidationDate: 'Fecha de liquidación',
   liquidationType: 'Tipo de liquidación',
   prefix: 'Prefijo',
   initialNumber: 'Número inicial',
   currentNumber: 'Número actutal',
   surname: 'Apellido',
   surnames: 'Apellidos',
   userName: 'Nombre de usuario',
   productDescription: 'Descripción del producto',
   homologationDescription: 'Descripción de homologación',
   discountAmount: 'Descuento',
   nandinaCode: 'Código nandina',
   discountAmountBc: 'Monto de descuento en Bs.',
   accountName: 'Nombre de cuenta',
   amount: 'Monto',
   budgetItemName: 'Nombre de partida',
   unitPrice: 'Precio unitario',
   unitMesurement: 'Unidad de medida',
   quantity: 'Cantidad',
   expenseBudget: 'Presupuesto de gasto',
   expenseBudgetSummary: 'Presupuesto de gasto',
   resourceBudgetSummary: 'Presupuesto de recurso',
   listOfCompanies: 'Lista de empresas',
   rmPercentage: 'RM porcentaje',
   royaltySilver: 'Regalia Plata',
   royaltyZinc: 'Regalia Zinc',
   royaltyLead: 'Regalia Plomo',
   cajaNacional: 'Caja Nacional',
   fedecomin: 'FEDECOMIN',
   fencomin: 'FENCOMIN',
   comibol: 'COMIBOL',
   royalties: 'Regalias',
   wilstermann: 'WILSTERMANN',
   cooperativeContribution: 'Contribución cooperativa',
   miningRoyalties: 'Regalías mineras',
   weakPassword: 'Contraseña débil',
   mediumPassword: 'Contraseña media',
   choosePassword: 'Escoja una contraseña',
   safePassword: 'Contraseña segura',
} as const);

export const TITLES = Object.freeze({
   customerList: 'Listado de clientes',
   customerAccountList: 'Listado de cuentas por cliente',
   homologationList: 'Listado de homologaciones',
   homologations: 'Homologaciones',
   items: 'Items',
   currencies: 'Monedas',
   invoiceDetails: 'Detalles de factura',
   customers: 'Clientes',
   invoices: 'Facturas',
   companies: 'Empresas',
   documentTypes: 'Tipos de documento',
   invoiceTypes: 'Tipos de factura',
   invoiceList: 'Listado de facturas',
   invoiceDetailList: 'Listado de detalles de factura',
} as const);

export const LABEL_BUTTONS = Object.freeze({
   create: 'Crear',
   cancel: 'Cancelar',
   clear: 'Limpiar',
   delete: 'Eliminar',
   edit: 'Editar',
   export: 'Exportar',
   expand: 'Mas información',
   filter: 'Filtrar',
   info: 'Info',
   reload: 'Actualizar',
   save: 'Guardar',
   cancelInvoice: 'Anular factura',
   printInvoice: 'Imprimir factura',
   search: 'Buscar',
   unassign: 'Desasignar',
   assign: 'Asignar',
   approve: 'Aprobar',
   deny: 'Rechazar',
   print: 'Imprimir',
} as const);

export const TOOLTIPS = Object.freeze({
   create: 'Crear',
   clear: 'Limpiar',
   clearFilters: 'Limpiar filtros',
   delete: 'Eliminar',
   edit: 'Editar',
   export: 'Exportar',
   info: 'Info',
   reload: 'Actualizar',
   selectColumns: 'Seleccione las columnas',
   homologateItem: 'Homologar item',
   close: 'Cerrar',
   save: 'Guardar',
   cancel: 'Cancelar',
   editableField: 'Este campo es editable',
   printInvoice: 'Imprimir factura',
   printLiquidation: 'Imprimir liquidación',
   conciliateInvoice: 'Conciliar factura',
   debitInvoice: 'Debitar factura',
   cancelInvoice: 'Anular factura',
   reverseAnnulment: 'Revertir anulación',
   issueInvoice: 'Emitir factura',
   massEditing: 'Edición masiva',
   massDeleting: 'Eliminación masiva',
   acceptChanges: 'Aceptar cambios',
   dismissChanges: 'Descartar Cambio',
   changePassword: 'Cambiar contraseña',
   editRow: 'Editar fila',
   deleteRow: 'Eliminar fila',
   uploadFile: 'Subir archivo',
   deleteFile: 'Borrar archivo',
} as const);

export const PLACEHOLDERS = Object.freeze({
   select: 'Seleccione una opción...',
   search: 'Buscar...',
   searchInCurrentView: 'Buscar en la vista actual',
   onDemandFilterInput: 'Ingrese 3 o más caracteres para buscar',
} as const);
