import { LIQUIDATION_TYPE_ENUM } from '@core/enums/liquidation-type';
import { DataBase } from './base-common.interface';

export interface Liquidation extends DataBase {
   id: number;
   supplierId: number;
   loadId: number;
   lotId: number;
   mineralId: number;
   mineId: number;
   cooperativeId: number;
   externalLot: string;
   correlativeLotCode: string;
   supplierName: string;
   mineralName: string;
   mineName: string;
   cooperativeName: string;
   cajaNacional: number;
   fedecomin: number;
   fencomin: number;
   comibol: number;
   wilstermann: number;
   cooperativeContribution: number;
   miningRoyalties: number;
   admissionDate: string;
   liquidationType: LIQUIDATION_TYPE_ENUM;
   liquidationDate: string;
   exchangeRate: number;
   priceSilver: number;
   priceZinc: number;
   priceLead: number;
   lawSilver: number;
   lawZinc: number;
   lawLead: number;
   humidityPercentage: number;
   metricWetKilograms: number;
   dryMetricKilograms: number;
   quotationSilver: number;
   quotationZinc: number;
   quotationLead: number;
   royaltySilver: number;
   royaltyZinc: number;
   royaltyLead: number;
   firstAdvance: number;
   secondAdvance: number;
   transportationBonus: number;
   amountPayableBc: number;
   amountPayableTc: number;
   totalPrice: number;
}
