import { DataBase } from './base-common.interface';

export interface PercentageLiquidation extends DataBase {
   id: number,
   loadId: number,
   supplierId: number,
   lotId: number,
   externalLot: string,
   correlativeLotCode: string,
   supplierName: string,
   cajaNacional: number,
   fedecomin: number,
   fencomin: number,
   comibol: number,
   miningRoyalties: number,
   admissionDate: string,
   percentageLiquidationDate: string,
   exchangeRate: number,
   quotation: number,
   percentage: number,
   dmSilver: number,
   humidityPercentage: number,
   metricWetKilograms: number,
   dryMetricKilograms: number,
   firstAdvance: number,
   transportation: number,
   amountPayableBc: number,
   amountPayableTc: number,
   totalPrice: number,
   discounts: number,
}
